name: gitleaks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        id: gitleaks
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  process-results:
    name: Process Results
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Get job_html_url
        run: |
           export repo="${{ github.repository }}"
           export workflow_run_id="${{ github.run_id }}"
           echo "https://api.github.com/repos/$repo/actions/runs/$workflow_run_id/artifacts"
           run_details=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$repo/actions/runs/$workflow_run_id/artifacts")
           echo "$run_details"
           url=$(echo "$run_details" | jq -r '.artifacts[0].archive_download_url')
           echo "$url"
           pwd
           ls -a
           
