name: gitleaks
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: two
        run: echo "Pull Request URL: https://github.com/${{ github.repository }}/pull/${{ github.sha }}"

