name: gitleaks
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: two
        run: echo "1 ${{ github.event.pull_request.number }}"

      - name: three
        run: echo "2 ${{ github.event.number }}"

