name: gitleaks
on:
  pull_request:
    types:
      - opened
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message Format
        run: echo  "${commit_sha}"
