name: gitleaks
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: two
        run: echo "${{github.server_url}}/${{github.repository}}/commit/${{github.sha}}"

