name: gitleaks
on:
  pull_request:
    types:
      - opened
  push:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:

      - name: three
        run: echo  "${{commit_sha}}"

