name: gitleaks
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: two
        run: echo " in ${{github.ref}} on ${{github.sha}}"

