name: gitleaks
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo ${{github.action}}
      - name: Dump job context
        run: echo ${{github.sha}}
      - name: Dump steps context
        run: echo "<https://github.com/${{ github.actor }}|${{ github.actor }}>
